@extends('template')

@section('style')
<style>
    .partner-admin-page{padding:28px;background:#f5f7fb;min-height:calc(100vh - 80px)}.partner-admin-wrap{max-width:1050px;margin:0 auto}.partner-admin-head{display:flex;justify-content:space-between;align-items:flex-start;gap:16px;margin-bottom:18px}.partner-admin-head h1{margin:0;color:#102a56}.partner-admin-head p{margin:6px 0;color:#64748b}.panel{background:#fff;border:1px solid #e2e8f0;border-radius:15px;padding:22px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.form-label{display:block;font-size:12px;font-weight:700;color:#475569;margin-bottom:4px}.form-control{width:100%;box-sizing:border-box;margin-bottom:13px}.section{border-top:1px solid #eef2f7;margin-top:18px;padding-top:18px}.section h2{font-size:17px;color:#102a56;margin:0 0 13px}.actions{display:flex;justify-content:flex-end;gap:8px;margin-top:18px}.btn{display:inline-block;border:0;border-radius:8px;padding:10px 13px;text-decoration:none;cursor:pointer;font-weight:700;font-size:12px;background:#2563eb;color:#fff}.btn.light{background:#eef2ff;color:#1d4ed8}.alert{padding:12px;background:#fef2f2;color:#b91c1c;border-radius:8px;margin-bottom:14px}@media(max-width:650px){.grid{grid-template-columns:1fr}.partner-admin-head{flex-direction:column}}
</style>
@endsection

@section('body')
<div class="partner-admin-page"><div class="partner-admin-wrap"><div class="partner-admin-head"><div><h1>{{ $isEdit ? 'Partner tahrirlash' : 'Yangi B2B partner' }}</h1><p>Partner kabinetiga kirish va filial ruxsatlarini shu yerdan boshqaring.</p></div><a class="btn light" href="{{ route('admin.partners.index') }}">Orqaga</a></div><div class="panel">
    @if($errors->any())<div class="alert">{{ $errors->first() }}</div>@endif
    <form method="POST" action="{{ $isEdit ? route('admin.partners.update',$partner) : route('admin.partners.store') }}">@csrf @if($isEdit)@method('PUT')@endif
        <div class="grid"><div><label class="form-label">Kompaniya nomi *</label><input class="form-control" name="company_name" value="{{ old('company_name',$partner->company_name) }}" required></div><div><label class="form-label">Code *</label><input class="form-control" name="code" value="{{ old('code',$partner->code) }}" pattern="[A-Za-z0-9_-]+" required></div></div>
        <div class="grid"><div><label class="form-label">Turi *</label><select class="form-control" name="type">@foreach($types as $type)<option value="{{ $type }}" @selected(old('type',$partner->type)===$type)>{{ $type }}</option>@endforeach</select></div><div><label class="form-label">Status *</label><select class="form-control" name="status"><option value="active" @selected(old('status',$partner->status)==='active')>Active</option><option value="suspended" @selected(old('status',$partner->status)==='suspended')>Suspended</option></select></div></div>
        <div class="grid"><div><label class="form-label">Kontakt shaxs</label><input class="form-control" name="contact_name" value="{{ old('contact_name',$partner->contact_name) }}"></div><div><label class="form-label">Telefon</label><input class="form-control" name="phone" value="{{ old('phone',$partner->phone) }}"></div></div>
        <div class="grid"><div><label class="form-label">Email</label><input class="form-control" type="email" name="email" value="{{ old('email',$partner->email) }}"></div><div><label class="form-label">Billing email</label><input class="form-control" type="email" name="billing_email" value="{{ old('billing_email',$partner->billing_email) }}"></div></div>
        <div class="grid"><div><label class="form-label">Tax ID</label><input class="form-control" name="tax_id" value="{{ old('tax_id',$partner->tax_id) }}"></div><div><label class="form-label">Valyuta *</label><input class="form-control" name="currency" value="{{ old('currency',$partner->currency ?: 'UZS') }}" maxlength="3" required></div></div>
        <div class="grid"><div><label class="form-label">Korporativ chegirma % *</label><input class="form-control" type="number" step="0.01" min="0" max="100" name="discount_percent" value="{{ old('discount_percent',$partner->discount_percent ?: 0) }}" required></div><div><label class="form-label">To‘lov muddati (kun) *</label><input class="form-control" type="number" min="0" max="365" name="payment_terms_days" value="{{ old('payment_terms_days',$partner->payment_terms_days ?: 30) }}" required></div></div>
        <div class="grid"><div><label class="form-label">Credit limit *</label><input class="form-control" type="number" step="0.01" min="0" name="credit_limit" value="{{ old('credit_limit',$partner->credit_limit ?: 0) }}" required></div><div><label class="form-label">Ruxsat berilgan filiallar *</label><select class="form-control" name="filial_ids[]" multiple required style="min-height:95px">@php($selectedFilials=collect(old('filial_ids',$partner->filials?->pluck('id')->all() ?: []))->map(fn($id)=>(int)$id)->all())@foreach($filials as $filial)<option value="{{ $filial->id }}" @selected(in_array($filial->id,$selectedFilials,true))>{{ $filial->name }}</option>@endforeach</select></div></div>
        <div class="section"><h2>White-label tracking</h2><div class="grid"><div><label class="form-label">Brand nomi</label><input class="form-control" name="brand_name" value="{{ old('brand_name',$partner->brand_name) }}"></div><div><label class="form-label">Logo URL</label><input class="form-control" type="url" name="brand_logo_url" value="{{ old('brand_logo_url',$partner->brand_logo_url) }}"></div></div><div class="grid"><div><label class="form-label">Primary rang *</label><input class="form-control" name="brand_primary_color" value="{{ old('brand_primary_color',$partner->trackingPrimaryColor()) }}" required></div><div><label class="form-label">Secondary rang *</label><input class="form-control" name="brand_secondary_color" value="{{ old('brand_secondary_color',$partner->trackingSecondaryColor()) }}" required></div></div><label class="form-label">Tracking sarlavhasi</label><input class="form-control" name="tracking_title" value="{{ old('tracking_title',$partner->tracking_title) }}"></div>
        @unless($isEdit)<div class="section"><h2>Partner kabineti administratori</h2><div class="grid"><div><label class="form-label">Ism *</label><input class="form-control" name="admin_name" value="{{ old('admin_name') }}" required></div><div><label class="form-label">Login *</label><input class="form-control" name="admin_login" value="{{ old('admin_login') }}" required></div></div><div class="grid"><div><label class="form-label">Telefon *</label><input class="form-control" name="admin_phone" value="{{ old('admin_phone') }}" required></div><div><label class="form-label">Parol *</label><input class="form-control" type="password" name="admin_password" required></div></div><label class="form-label">Parolni tasdiqlash *</label><input class="form-control" type="password" name="admin_password_confirmation" required></div>@endunless
        <div class="section"><label class="form-label">Ichki izoh</label><textarea class="form-control" name="notes" rows="3">{{ old('notes',$partner->notes) }}</textarea></div><div class="actions"><a class="btn light" href="{{ route('admin.partners.index') }}">Bekor qilish</a><button class="btn" type="submit">{{ $isEdit ? 'Saqlash' : 'Partner yaratish' }}</button></div>
    </form>
</div></div></div>
@endsection
