@extends('template')

@section('style')
<style>
.pricing-page{padding:28px;background:#f5f7fb;min-height:calc(100vh - 80px)}.pricing-wrap{max-width:1000px;margin:0 auto}.pricing-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;margin-bottom:18px}.pricing-head h1{margin:0;color:#102a56}.panel{background:#fff;border:1px solid #e2e8f0;border-radius:15px;padding:22px;box-shadow:0 8px 24px rgba(15,23,42,.04)}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.form-label{display:block;font-size:12px;font-weight:700;color:#475569;margin-bottom:4px}.form-control,.form-select{width:100%;box-sizing:border-box;margin-bottom:13px}.section{border-top:1px solid #eef2f7;margin-top:18px;padding-top:18px}.btn{display:inline-block;border:0;border-radius:8px;padding:10px 13px;text-decoration:none;cursor:pointer;font-weight:700;font-size:12px;background:#2563eb;color:#fff}.btn.light{background:#eef2ff;color:#1d4ed8}.alert{padding:12px;background:#fef2f2;color:#b91c1c;border-radius:8px;margin-bottom:14px}.actions{display:flex;justify-content:flex-end;gap:8px;margin-top:18px}@media(max-width:700px){.grid{grid-template-columns:1fr}.pricing-head{flex-direction:column}}
</style>
@endsection

@section('body')
<div class="pricing-page"><div class="pricing-wrap"><div class="pricing-head"><div><h1>{{ $isEdit ? 'Tarifni tahrirlash' : 'Yangi tarif versiyasi' }}</h1><p>Effective davrlar kesishmasin. Ishlatilgan tarif narxi immutable hisoblanadi.</p></div><a class="btn light" href="{{ route('admin.pricing.index') }}">Orqaga</a></div><div class="panel">
    @if($errors->any())<div class="alert">{{ $errors->first() }}</div>@endif
    <form method="POST" action="{{ $isEdit ? route('admin.pricing.update',$tariff) : route('admin.pricing.store') }}">@csrf @if($isEdit)@method('PUT')@endif
        <div class="grid"><div><label class="form-label">Price line turi *</label><select class="form-select" name="line_type" required>@foreach($lineTypes as $type)<option value="{{ $type }}" @selected(old('line_type',$tariff->line_type)===$type)>{{ $type }}</option>@endforeach</select></div><div><label class="form-label">Variant *</label><select class="form-select" name="variant" required>@foreach($variants as $variant)<option value="{{ $variant }}" @selected(old('variant',$tariff->variant)===$variant)>{{ $variant }}</option>@endforeach</select></div></div>
        <div class="grid"><div><label class="form-label">Xizmat</label><select class="form-select" name="service_id"><option value="">—</option>@foreach($services as $service)<option value="{{ $service->id }}" @selected((string)old('service_id',$tariff->service_id)===(string)$service->id)>{{ $service->name }}</option>@endforeach</select></div><div><label class="form-label">Service addon</label><select class="form-select" name="service_addon_id"><option value="">—</option>@foreach($addons as $addon)<option value="{{ $addon->id }}" @selected((string)old('service_addon_id',$tariff->service_addon_id)===(string)$addon->id)>{{ $addon->service?->name }} / {{ $addon->name }}</option>@endforeach</select></div></div>
        <div class="grid"><div><label class="form-label">Price key</label><input class="form-control" name="price_key" value="{{ old('price_key',$tariff->price_key) }}" placeholder="courier:tashkent"></div><div><label class="form-label">Source ID</label><input class="form-control" type="number" min="1" name="source_id" value="{{ old('source_id',$tariff->source_id) }}"></div></div>
        <div class="grid"><div><label class="form-label">Filial</label><select class="form-select" name="filial_id"><option value="">Barcha filiallar</option>@foreach($filials as $filial)<option value="{{ $filial->id }}" @selected((string)old('filial_id',$tariff->filial_id)===(string)$filial->id)>{{ $filial->name }}</option>@endforeach</select></div><div><label class="form-label">Corporate partner</label><select class="form-select" name="partner_id"><option value="">Barcha partnerlar</option>@foreach($partners as $partner)<option value="{{ $partner->id }}" @selected((string)old('partner_id',$tariff->partner_id)===(string)$partner->id)>{{ $partner->company_name }}</option>@endforeach</select></div></div>
        <div class="grid"><div><label class="form-label">Nomi *</label><input class="form-control" name="name" value="{{ old('name',$tariff->name) }}" required></div><div><label class="form-label">Season code</label><input class="form-control" name="season_code" value="{{ old('season_code',$tariff->season_code) }}" placeholder="summer-2026"></div></div>
        <div class="grid"><div><label class="form-label">Sotuv narxi *</label><input class="form-control" type="number" step="0.01" min="0" name="price" value="{{ old('price',$tariff->price) }}" required></div><div><label class="form-label">Tannarx</label><input class="form-control" type="number" step="0.01" min="0" name="cost_amount" value="{{ old('cost_amount',$tariff->cost_amount ?: 0) }}"></div></div>
        <div class="grid"><div><label class="form-label">Deadline (kun/soat)</label><input class="form-control" type="number" min="0" name="deadline" value="{{ old('deadline',$tariff->deadline ?: 0) }}"></div><div><label class="form-label">Priority</label><input class="form-control" type="number" min="0" name="priority" value="{{ old('priority',$tariff->priority ?: 0) }}"></div></div>
        <div class="grid"><div><label class="form-label">Effective from *</label><input class="form-control" type="datetime-local" name="effective_from" value="{{ old('effective_from',optional($tariff->effective_from)->format('Y-m-d\\TH:i')) }}" required></div><div><label class="form-label">Effective to</label><input class="form-control" type="datetime-local" name="effective_to" value="{{ old('effective_to',optional($tariff->effective_to)->format('Y-m-d\\TH:i')) }}"></div></div>
        <div class="grid"><div><label class="form-label">Currency *</label><input class="form-control" name="currency" maxlength="3" value="{{ old('currency',$tariff->currency ?: 'UZS') }}" required></div><div class="form-check" style="padding-top:28px"><input class="form-check-input" type="checkbox" name="is_active" value="1" @checked(old('is_active',$tariff->is_active))><label class="form-check-label">Faol tarif</label></div></div>
        <div class="actions"><a class="btn light" href="{{ route('admin.pricing.index') }}">Bekor qilish</a><button class="btn" type="submit">{{ $isEdit ? 'Saqlash' : 'Tarif yaratish' }}</button></div>
    </form>
</div></div></div>
@endsection
