@extends('template')

@section('style')
<style>
.pricing-page{padding:28px;background:#f5f7fb;min-height:calc(100vh - 80px)}.pricing-wrap{max-width:1400px;margin:0 auto}.pricing-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;margin-bottom:18px}.pricing-head h1{margin:0;color:#102a56}.pricing-head p{margin:6px 0;color:#64748b}.panel{background:#fff;border:1px solid #e2e8f0;border-radius:15px;padding:20px;box-shadow:0 8px 24px rgba(15,23,42,.04)}.toolbar{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:15px}.toolbar input,.toolbar select{max-width:220px}.btn{display:inline-block;border:0;border-radius:8px;padding:10px 13px;text-decoration:none;cursor:pointer;font-weight:700;font-size:12px;background:#2563eb;color:#fff}.btn.light{background:#eef2ff;color:#1d4ed8}table{width:100%;border-collapse:collapse}th,td{padding:10px 8px;text-align:left;border-bottom:1px solid #eef2f7;font-size:12px;vertical-align:top}th{font-size:10px;color:#64748b;text-transform:uppercase}.muted{color:#64748b;font-size:11px}.badge{display:inline-block;background:#f1f5f9;border-radius:999px;padding:4px 8px;font-size:10px}.active{background:#dcfce7;color:#166534}.notice{padding:12px;background:#ecfdf5;color:#047857;border-radius:8px;margin-bottom:14px}@media(max-width:900px){.panel{overflow:auto}.pricing-head{flex-direction:column}}
</style>
@endsection

@section('body')
<div class="pricing-page"><div class="pricing-wrap">
    @if(session('success'))<div class="notice">{{ session('success') }}</div>@endif
    <div class="pricing-head"><div><h1>Tariflar va narxlar tarixi</h1><p>Har bir yangi tarif alohida versiya. Ishlatilgan tarifning narxi o‘zgartirilmaydi.</p></div><div><a class="btn light" href="{{ route('pricing.approvals.index') }}">Chegirma approval’lari</a> <a class="btn" href="{{ route('admin.pricing.create') }}">+ Yangi tarif</a></div></div>
    <div class="panel"><form class="toolbar" method="GET"><input class="form-control" name="q" value="{{ request('q') }}" placeholder="Nom yoki price key"><select class="form-select" name="filial_id"><option value="">Barcha filiallar</option>@foreach($filials as $filial)<option value="{{ $filial->id }}" @selected((string)request('filial_id')===(string)$filial->id)>{{ $filial->name }}</option>@endforeach</select><select class="form-select" name="line_type"><option value="">Barcha satrlar</option>@foreach($lineTypes as $type)<option value="{{ $type }}" @selected(request('line_type')===$type)>{{ $type }}</option>@endforeach</select><select class="form-select" name="variant"><option value="">Barcha variantlar</option>@foreach($variants as $variant)<option value="{{ $variant }}" @selected(request('variant')===$variant)>{{ $variant }}</option>@endforeach</select><button class="btn light">Filtrlash</button></form>
        <table><thead><tr><th>Satr</th><th>Manba</th><th>Kontekst</th><th>Narx / tannarx</th><th>Amal qilish davri</th><th>Holat</th><th></th></tr></thead><tbody>
        @forelse($tariffs as $tariff)<tr><td><strong>{{ $tariff->name }}</strong><br><span class="muted">{{ $tariff->line_type }}</span></td><td>{{ $tariff->service?->name ?: $tariff->serviceAddon?->name ?: ($tariff->price_key ?: $tariff->source_id ?: 'Global') }}<br><span class="muted">{{ $tariff->filial?->name ?: 'Barcha filial' }} · {{ $tariff->partner?->company_name ?: 'Barcha partner' }}</span></td><td><span class="badge">{{ $tariff->variant }}</span>@if($tariff->season_code)<br><span class="muted">{{ $tariff->season_code }}</span>@endif</td><td>{{ number_format((float)$tariff->price,2,',',' ') }} {{ $tariff->currency }}<br><span class="muted">Tannarx: {{ number_format((float)$tariff->cost_amount,2,',',' ') }}</span></td><td>{{ optional($tariff->effective_from)->format('d.m.Y H:i') }}<br><span class="muted">→ {{ optional($tariff->effective_to)->format('d.m.Y H:i') ?: 'ochiq' }}</span></td><td><span class="badge {{ $tariff->is_active ? 'active' : '' }}">{{ $tariff->is_active ? 'active' : 'inactive' }}</span></td><td><a class="btn light" href="{{ route('admin.pricing.edit',$tariff) }}">Tahrirlash</a></td></tr>@empty<tr><td colspan="7" class="muted">Tariflar hali yo‘q.</td></tr>@endforelse
        </tbody></table>{{ $tariffs->links() }}
    </div>
</div></div>
@endsection
