@extends('template')
@section('style')
<style>.partner-page{padding:26px;background:#f5f7fb;min-height:calc(100vh - 80px)}.partner-wrap{max-width:980px;margin:0 auto}.partner-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;margin-bottom:18px}.partner-head h1{margin:0;color:#102a56}.partner-head p{margin:6px 0;color:#64748b}.panel{background:#fff;border:1px solid #e2e8f0;border-radius:15px;padding:22px}.row-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.form-label{display:block;font-size:12px;font-weight:700;color:#475569;margin-bottom:4px}.form-control{width:100%;box-sizing:border-box;margin-bottom:13px}.product-card{border:1px solid #bfdbfe;border-radius:12px;padding:14px;background:#eff6ff;margin:8px 0 14px}.product-meta{display:flex;gap:8px;flex-wrap:wrap;margin-top:8px}.badge{display:inline-block;background:#fff;border-radius:999px;padding:6px 10px;font-size:12px;color:#475569}.actions{display:flex;justify-content:flex-end;gap:8px;flex-wrap:wrap}.btn{display:inline-block;border:0;border-radius:8px;padding:10px 13px;text-decoration:none;cursor:pointer;font-weight:700;font-size:12px;background:#2563eb;color:#fff}.btn.light{background:#eef2ff;color:#1d4ed8}.alert{padding:12px;background:#fef2f2;color:#b91c1c;border-radius:8px;margin-bottom:14px}@media(max-width:650px){.row-grid{grid-template-columns:1fr}.partner-head{flex-direction:column}}</style>
@endsection
@section('body')
<div class="partner-page"><div class="partner-wrap"><div class="partner-head"><div><h1>Yangi B2B buyurtma</h1><p>{{ $partner->company_name }} uchun korporativ chegirma avtomatik qo‘llanadi.</p></div><a class="btn light" href="{{ route('partner.orders.index') }}">Orqaga</a></div>
    <div class="panel">@if($errors->any())<div class="alert">{{ $errors->first() }}</div>@endif @if(!$filials->count())<div class="alert">Sizga hali filial biriktirilmagan. Administrator filialni ruxsat ro‘yxatiga qo‘shishi kerak.</div>@else
    <form method="POST" action="{{ route('partner.orders.store') }}" id="partnerOrderForm">@csrf
        <div class="row-grid"><div><label class="form-label">Filial</label><select class="form-control" name="filial_id" id="filialSelect" required>@foreach($filials as $filial)<option value="{{ $filial->id }}" @selected((string)old('filial_id',$selectedFilialId)===(string)$filial->id)>{{ $filial->name }}</option>@endforeach</select></div><div><label class="form-label">Partner reference</label><input class="form-control" name="partner_reference" value="{{ old('partner_reference') }}" placeholder="Universitet ID yoki invoice reference"></div></div>
        <div class="row-grid"><div><label class="form-label">Mijoz F.I.Sh.</label><input class="form-control" name="client_name" value="{{ old('client_name') }}" required></div><div><label class="form-label">Mijoz telefoni</label><input class="form-control" name="client_phone" value="{{ old('client_phone') }}" required></div></div>
        <div class="row-grid"><div><label class="form-label">Mijoz emaili</label><input class="form-control" type="email" name="client_email" value="{{ old('client_email') }}"></div><div><label class="form-label">Buyurtma nomi</label><input class="form-control" name="title" value="{{ old('title') }}" placeholder="Masalan: Student visa batch"></div></div>
        <div class="row-grid"><div><label class="form-label">Sotiladigan paket</label><select class="form-control" name="package_template_id" id="packageSelect"><option value="">Oddiy order</option></select></div><div><label class="form-label">Variant</label><div style="padding:10px 0"><label><input type="radio" name="package_variant" value="standard" @checked(old('package_variant','standard')==='standard')> Standard</label> <label style="margin-left:15px"><input type="radio" name="package_variant" value="express" @checked(old('package_variant')==='express')> Express</label></div></div></div>
        <div id="packagePreview" class="product-card" style="display:none"></div><div id="addonBox" style="margin-bottom:14px"></div>
        <div class="row-grid"><div><label class="form-label">Yetkazib berish</label><select class="form-control" name="delivery_type"><option value="pickup">Filialdan olish</option><option value="courier">Kuryer</option><option value="digital">Digital</option><option value="branch">Boshqa filial</option></select></div><div><label class="form-label">Deadline</label><input class="form-control" type="datetime-local" name="promised_at" value="{{ old('promised_at') }}"></div></div>
        <div class="row-grid"><div><label class="form-label">Prioritet</label><select class="form-control" name="priority"><option value="normal">Oddiy</option><option value="high">Yuqori</option><option value="urgent">Shoshilinch</option></select></div><div><label class="form-label">Izoh</label><textarea class="form-control" name="description" rows="2">{{ old('description') }}</textarea></div></div>
        <div class="actions"><a class="btn light" href="{{ route('partner.dashboard') }}">Bekor qilish</a><button class="btn" type="submit">Buyurtma yaratish</button></div>
    </form>@endif</div></div></div>
@endsection
@section('script')
<script>
(function(){const catalog=@json($catalogByFilial);const filial=document.getElementById('filialSelect');const select=document.getElementById('packageSelect');const preview=document.getElementById('packagePreview');const addons=document.getElementById('addonBox');const oldId=@json(old('package_template_id'));const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));const money=v=>Number(v||0).toLocaleString('uz-UZ')+' so\'m';function list(){return catalog[filial?.value]||[]}function renderOptions(){const current=select.value||oldId;select.innerHTML='<option value="">Oddiy order</option>';list().forEach(p=>{const o=document.createElement('option');o.value=p.id;o.textContent=p.code+' — '+p.name;o.selected=String(p.id)===String(current);select.appendChild(o)});render()}function render(){const p=list().find(x=>String(x.id)===String(select.value));if(!p){preview.style.display='none';addons.innerHTML='';return}const v=document.querySelector('input[name="package_variant"]:checked')?.value||'standard';const q=p[v]||p.standard;preview.innerHTML='<strong>'+esc(p.name)+'</strong><div class="product-meta"><span class="badge">'+esc(p.code)+'</span><span class="badge">'+(v==='express'?'Express':'Standard')+': '+money(q.price)+'</span><span class="badge">'+q.deadline_days+' kun</span><span class="badge">Partner chegirmasi: '+{{ (float)$partner->discount_percent }}+'%</span></div>';preview.style.display='block';const a=p.additional_services||[];addons.innerHTML=a.length?'<label class="form-label">Qo‘shimcha xizmatlar</label>'+a.map(x=>'<label style="display:block;margin:6px 0"><input type="checkbox" name="package_addon_ids[]" value="'+x.id+'"> '+esc(x.name)+' — '+money(x.price)+'</label>').join(''):''}filial?.addEventListener('change',renderOptions);select?.addEventListener('change',render);document.querySelectorAll('input[name="package_variant"]').forEach(x=>x.addEventListener('change',render));if(select)renderOptions()})();
</script>
@endsection
