@extends('template')
@section('style')
    @include('partner.partials.styles')
@endsection
@section('body')
<div class="partner-page"><div class="partner-wrap"><div class="partner-head"><div><h1>{{ $order->order_code }}</h1><p class="muted">{{ $order->partner_reference ?: 'Partner reference ko‘rsatilmagan' }} · {{ $order->filial?->name }}</p></div><div class="partner-actions"><a class="btn light" href="{{ route('partner.orders.index') }}">Buyurtmalar</a><a class="btn" href="{{ route('orders.partner-track', ['partnerCode'=>$partner->code, 'trackingToken'=>$order->tracking_token]) }}" target="_blank">White-label tracking</a></div></div>
<div class="panel"><div class="row"><span>Status</span><strong>{{ $order->status_label }}</strong></div><div class="row"><span>Billing</span><strong>{{ $order->billing_status }}</strong></div><div class="row"><span>Mijoz</span><strong>{{ $order->client?->name }} · {{ $order->client?->phone_number }}</strong></div><div class="row"><span>Paket</span><strong>{{ $order->packageTemplate?->name ?: 'Oddiy order' }} @if($order->package_variant)({{ $order->package_variant }})@endif</strong></div><div class="row"><span>Summa</span><strong>{{ number_format($order->total_amount,0,',',' ') }} {{ $order->currency }}</strong></div><div class="row"><span>Chegirma</span><strong>{{ number_format($order->discount_amount,0,',',' ') }} {{ $order->currency }}</strong></div><div class="row"><span>To‘langan / qoldiq</span><strong>{{ number_format($order->paid_amount,0,',',' ') }} / {{ number_format($order->balance_amount,0,',',' ') }} {{ $order->currency }}</strong></div></div>
<div class="panel" style="margin-top:16px"><h2>Price lines</h2><table><thead><tr><th>Xizmat</th><th>Miqdor</th><th>Jami</th></tr></thead><tbody>@forelse($order->priceLines as $line)<tr><td>{{ $line->name }}</td><td>{{ $line->quantity }}</td><td>{{ number_format($line->total_price,0,',',' ') }} {{ $order->currency }}</td></tr>@empty<tr><td colspan="3" class="muted">Price line yo‘q.</td></tr>@endforelse</tbody></table></div>
<div class="panel" style="margin-top:16px"><h2>Status tarixi</h2>@forelse($order->statusHistories as $history)<div class="row"><span>{{ \App\Models\Order::STATUS_LABELS[$history->to_status] ?? $history->to_status }}</span><span class="muted">{{ optional($history->created_at)->format('d.m.Y H:i') }}</span></div>@empty<span class="muted">Tarix yo‘q.</span>@endforelse</div>
</div></div>
@endsection
