@extends('template')

@section('body')
<div class="page-wrapper"><div class="page-content">
    <div class="d-flex flex-wrap justify-content-between align-items-center mb-4"><div><h4 class="mb-1">Mening bugungi ishlarim</h4><p class="text-muted mb-0">Sizning rolingiz uchun vaqt va qaror talab qilayotgan ishlar.</p></div><div class="d-flex gap-2"><a class="btn btn-outline-primary" href="{{ route('leads.index') }}">Leadlar</a>@hasanyrole('admin_manager|super_admin')<a class="btn btn-outline-warning" href="{{ route('operations.approvals.index') }}">Tasdiqlar ({{ $counts['approvals'] }})</a>@endhasanyrole</div></div>
    <div class="row row-cols-2 row-cols-lg-6 g-3 mb-4">@foreach([['Mening ishlarim',$counts['tasks'],'primary'],['Deadline xavfi',$counts['risk'],'danger'],['Qarzdor tayyor',$counts['debt'],'warning'],['QA navbati',$counts['qa'],'info'],['Lead follow-up',$counts['leads'],'secondary'],['Tasdiqlar',$counts['approvals'],'dark']] as [$label,$value,$color])<div class="col"><div class="card border-0 shadow-sm h-100"><div class="card-body"><small class="text-muted">{{ $label }}</small><div class="fs-3 fw-bold text-{{ $color }}">{{ $value }}</div></div></div></div>@endforeach</div>
    <div class="row g-4"><div class="col-xl-7"><div class="card shadow-sm mb-4"><div class="card-header bg-white fw-bold">Mening action navbatim</div><div class="list-group list-group-flush">@forelse($tasks as $task)<div class="list-group-item d-flex justify-content-between gap-3"><div><span class="badge text-bg-{{ $task->priority === 'urgent' ? 'danger' : ($task->priority === 'high' ? 'warning' : 'secondary') }}">{{ $task->priority }}</span> <strong>{{ $task->title }}</strong><small class="d-block text-muted">{{ $task->lead?->phone ?: $task->order?->order_code }} · {{ optional($task->due_at)->format('d.m H:i') ?: 'muddat yo‘q' }}</small></div><form method="POST" action="{{ route('operations.work-items.complete',$task) }}">@csrf<button class="btn btn-sm btn-outline-success">Bajarildi</button></form></div>@empty<div class="list-group-item text-muted">Ochiq individual ish yo‘q.</div>@endforelse</div></div>
        <div class="card shadow-sm"><div class="card-header bg-white fw-bold">Deadline xavfidagi orderlar</div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Order</th><th>Risk</th><th>Sabab</th></tr></thead><tbody>@forelse($riskOrders as $item)<tr><td><a href="{{ route('orders.show',$item['order']) }}">{{ $item['order']->order_code }}</a><small class="d-block">{{ $item['order']->client?->name }}</small></td><td><span class="badge text-bg-{{ $item['risk']['level']==='red'?'danger':'warning' }}">{{ $item['risk']['score'] }}/100</span></td><td>{{ implode('; ', $item['risk']['reasons']) }}</td></tr>@empty<tr><td colspan="3" class="text-muted text-center p-4">Risk topilmadi.</td></tr>@endforelse</tbody></table></div></div></div>
        <div class="col-xl-5"><div class="card shadow-sm mb-4"><div class="card-header bg-white fw-bold">Bugun lead bilan bog‘lanish</div><div class="list-group list-group-flush">@forelse($leadFollowUps as $lead)<a href="{{ route('leads.index') }}#lead-{{ $lead->id }}" class="list-group-item list-group-item-action"><strong>{{ $lead->name }}</strong><small class="d-block text-muted">{{ $lead->phone }} · {{ $lead->source ?: 'Manba noma’lum' }} · {{ optional($lead->next_follow_up_at)->format('d.m H:i') }}</small></a>@empty<div class="list-group-item text-muted">Follow-up yo‘q.</div>@endforelse</div></div>
        <div class="card shadow-sm mb-4"><div class="card-header bg-white fw-bold">Tayyor, ammo qarzdor</div><div class="list-group list-group-flush">@forelse($readyWithDebt as $order)<a class="list-group-item list-group-item-action" href="{{ route('orders.show',$order) }}"><strong>{{ $order->order_code }}</strong><span class="float-end text-danger">{{ number_format($order->balance_amount,0,',',' ') }}</span><small class="d-block text-muted">{{ $order->client?->name }}</small></a>@empty<div class="list-group-item text-muted">Bunday order yo‘q.</div>@endforelse</div></div>
        <div class="card shadow-sm"><div class="card-header bg-white fw-bold">QA navbati</div><div class="list-group list-group-flush">@forelse($qaQueue as $document)<a class="list-group-item list-group-item-action" href="{{ route('documents.workflow.index') }}"><strong>{{ $document->document_code }}</strong><small class="d-block text-muted">{{ $document->order?->order_code }} · {{ $document->status_doc }}</small></a>@empty<div class="list-group-item text-muted">QA navbati bo‘sh.</div>@endforelse</div></div></div></div>
</div></div>
@endsection
